apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "beskar-yum.fullname" . }}
rules:
  - apiGroups:
    - ''
    resources:
      - endpoints
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "beskar-yum.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name | default (include "beskar-yum.fullname" .) }}
    apiGroup: ""
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "beskar-yum.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
