apiVersion: v1
kind: Service
metadata:
  name: {{ include "beskar-yum.fullname" . }}
  labels:
    {{- include "beskar-yum.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5200
      protocol: TCP
      name: http
  selector:
    {{- include "beskar-yum.selectorLabels" . | nindent 4 }}
