apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "beskar.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "beskar.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "beskar.selectorLabels" . | nindent 6 }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- if .Values.updateStrategy }}
  strategy: {{ toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  minReadySeconds: 5
  template:
    metadata:
      labels:
        {{- include "beskar.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        {{ toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | default (include "beskar.fullname" .) }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - /usr/bin/beskar
          - -config-dir=/etc/beskar
          ports:
            - containerPort: 5000
              name: {{ if .Values.tlsSecretName }}https{{ else }}http{{ end }}-{{ .Values.services.registry.port }}
              protocol: TCP
            - containerPort: 5002
              name: gossip-tcp
              protocol: TCP
            - containerPort: 5002
              name: gossip-udp
              protocol: UDP
            - containerPort: 5003
              name: groupcache
              protocol: TCP
            {{- if .Values.metrics.enabled }}
            - containerPort: {{ (split ":" .Values.configData.registry.http.debug.addr)._1 }}
              name: http-metrics
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              {{- if .Values.tlsSecretName }}
              scheme: HTTPS
              {{- end }}
              path: /
              port: 5000
          readinessProbe:
            httpGet:
              {{- if .Values.tlsSecretName }}
              scheme: HTTPS
              {{- end }}
              path: /
              port: 5000
          resources: {{ toYaml .Values.resources | nindent 12 }}
          env: {{ include "beskar.envs" . | nindent 12 }}
          volumeMounts: {{ include "beskar.volumeMounts" . | nindent 12 }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      volumes: {{ include "beskar.volumes" . | nindent 8 }}
