apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "beskar.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
{{- if .Values.serviceAccount.name }}
  name: {{ .Values.serviceAccount.name }}
{{- else  }}
  name: {{ include "beskar.fullname" . }}
{{- end }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- end }}
